version: "3"
services:
  ui:
    build: ./social-ui
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_FACEBOOK_API_URL=https://graph.facebook.com/v18.0
      - FACEBOOK_USER_ID=1088139082594223
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  api:
    build: ./social-api
    environment:
      - NODE_ENV=development
      - PORT=8000
      - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
      - JWT_EXPIRATION_MINUTES=3000
      - MONGO_URI=mongodb://localhost:27017/skipli
      - MONGO_URI_TEST=mongodb://localhost:27017/skipli
      - RATE_LIMIT_TIME=15
      - RATE_LIMIT_REQUEST=15
      - ACCOUNT_SID=ACd30f1f490a1adb977b543496c9295678
      - AUTH_TOKEN=516cf88f35fcb6b73367b7d9a9692f26
      - VERIFY_SID=VAf533b43ed703cbaa0b33369217e38a6e
      - REDIS_HOST=redisdb
      - REDIS_PORT=6379
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - mongodb
      - redisdb
    depends_on:
      - mongodb
      - redisdb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  redisdb:
    image: redis
    ports:
      - "6379:6379"
