version: "3"
services:
  # ui:
  #   build: ./my-app
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #     - NEXT_PUBLIC_FB_API_URL=https://graph.facebook.com/v18.0
  #     - FB_USER_ID=1088139082594223
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3000:3000"

  # api:
  #   build: ./node-express-es8
  #   command: npm run start
  #   environment:
  #     - NODE_ENV=production
  #     - MONGO_URI=mongodb://mongodb:27017/node-es8-boilerplate
  #     - PORT=8000
  #     - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
  #     - JWT_EXPIRATION_MINUTES=15
  #     - RATE_LIMIT_TIME=15
  #     - RATE_LIMIT_REQUEST=15
  #     - REDIS_HOST=redisdb
  #     - REDIS_PORT=6379
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   links:
  #     - mongodb
  #     - redisdb
  #   depends_on:
  #     - mongodb
  #     - redisdb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  redisdb:
    image: redis
    ports:
      - "6379:6379"
